spring.application.name=votacao


spring.datasource.url=jdbc:postgresql://localhost:5495/desafio_votacao&connectTimeout=20&socketTimeout=60&tcpKeepAlive=true
spring.datasource.username=votacao
spring.datasource.password=z896ipGG012567
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Propriedade para aumentar o pool de conexões
spring.datasource.hikari.maximum-pool-size=30

# Propriedade para manter pelo menos 10 conexões ociosas
spring.datasource.hikari.minimum-idle=10

# Propriedade para definir o tempo máximo de espera para obter uma conexão
spring.datasource.hikari.max-lifetime=1680000

# Propriedade para definir o tempo máximo de espera para uma conexão ociosa
spring.datasource.hikari.idle-timeout=10000

# Propriedade para para aumentar as threads do Tomcat assim conseguindo trabalhar com mais requisições ao mesmo tempo
server.tomcat.max-threads=100

# Propriedade que aumenta o numero de requisições que podem ficar em fila
server.tomcat.accept-count=1000

# Propriedade que define número máximo total de conexões simultâneas
server.tomcat.max-connections=2000